services:
  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/18/data
      - ./infra/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    restart: unless-stopped
    tty: true
    stdin_open: true

  user_service:
    build: ./user_service
    container_name: user_service
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./user_service:/app
      - /app/.venv
      - /app/__pycache__
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload


  experiment_service:
      build: ./experiment_manager
      container_name: experiment_service
      env_file:
        - ./.env
      ports:
        - "8001:8000"
      volumes:
        - ./experiment_manager:/app
        - /app/.venv
        - /app/__pycache__
      command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  model_registry_service:
      build: ./model_registry
      container_name: model_service
      env_file:
        - ./.env
      ports:
        - "8002:8000"
      volumes:
        - ./model_registry:/app
        - /app/.venv
        - /app/__pycache__
      command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  pgdata:
    driver: local
