services:

###################### INFRASTRUCTURE ######################
  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/18/data
      - ./infra/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    restart: unless-stopped
    tty: true
    stdin_open: true
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend_network
      - ml_network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    env_file:
      - ./.env
    networks:
      - ml_network


  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "kafka-cluster cluster-id --bootstrap-server localhost:9092 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - ml_network

  kafka-init:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./infra/kafka_init.sh:/init.sh
    entrypoint: ["/bin/sh", "/init.sh"]
    networks:           
      - ml_network

  redis:
    image: redis:7
    command: redis-server --appendonly yes --appendfsync everysec
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - ml_network

  ray-head:
      image: rayproject/ray:2.55.1-py313
      container_name: ray-head
      ports:
        - "8265:8265"
        - "8010:8000"
        - "6379:6379"
        - "10001:10001"
      command: >
        ray start --head --port=6379 --dashboard-host=0.0.0.0 --include-dashboard=true --block
      #volumes:
      #  - ./shared_data:/tmp/ray
      networks:
        - ml_network

###################### APP ######################

  user_service:
    build: ./services/user_service
    container_name: user_service
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./services/user_service:/app
      - /app/.venv
      - /app/__pycache__
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - backend_network
    depends_on:
      postgres:
        condition: service_healthy


  experiment_service:
    build: ./services/experiment_manager
    container_name: experiment_service
    env_file:
      - ./.env
    ports:
      - "8001:8000"
    volumes:
      - ./services/experiment_manager:/app
      - /app/.venv
      - /app/__pycache__
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - backend_network
    depends_on:
      postgres:
        condition: service_healthy


  model_registry_service:
    build: ./services/model_registry
    container_name: model_registry
    env_file:
      - ./.env
    ports:
      - "8002:8000"
    volumes:
      - ./services/model_registry:/app
      - /app/.venv
      - /app/__pycache__
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - ml_network
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy

  model_serving_service:
    build: ./services/model_serving
    container_name: model_serving
    env_file:
      - ./.env
    ports:
      - "8003:8080"
    volumes:
      - ./services/model_serving:/app
      - /app/.venv
      - /app/__pycache__
    command: faststream run app.main:app --host 0.0.0.0 --port 8080 --reload
    networks:
      - ml_network
    depends_on:
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy

  traffic_splitter:
    build:
      context: .
      dockerfile: ./services/traffic_splitter/Dockerfile
    container_name: traffic_splitter
    env_file:
      - ./.env
    ports:
      - "50051:50051"
    networks:
      - backend_network
      - ml_network
    #depends_on:
    #  experiment_service:
    #    condition: service_healthy
    #  model_registry_service:
    #    condition: service_healthy

  api-gateway:
    build:
      context: .
      dockerfile: ./services/api_gateway/Dockerfile
    container_name: api_gateway
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    networks:
      - backend_network
      - ml_network
    depends_on:
      user_service:
        condition: service_started
      experiment_service:
        condition: service_started
      model_registry_service:
        condition: service_started
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
      


  ###################### UI ######################
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_JMXPORT: 9997
      DYNAMIC_CONFIG_ENABLED: 'true'
    depends_on:
      - kafka
      - zookeeper
    networks:
      - ml_network
    restart: unless-stopped

volumes:
  pgdata:
    driver: local

networks:
  backend_network:
    driver: bridge
  ml_network:
    driver: bridge
