from typing import Protocol

from domain.user.entities import User


class UserRepo(Protocol):
    async def get_by_id(self, id: int) -> User: ...
    async def get_by_username_or_email(self, login: str) -> User: ...
    async def get_by_username(self, username: str) -> User: ...
    async def save(self, user: User) -> User: ...
    async def delete(self, user_id: int) -> None: ...
