syntax = "proto3";
package splitter.v1;

option go_package = "github.com/tahion/ml_ab_test_service/gen/go/splitter/v1;splitterv1";

service TrafficSplitter {
  rpc GetVariant(GetVariantRequest) returns (GetVariantResponse);

  rpc GetVariants(GetVariantsRequest) returns (GetVariantsResponse);
}

message GetVariantRequest {
  string user_id = 1;
  string experiment_id = 2;
  map<string, string> attributes = 3;
}

message GetVariantResponse {
  string variant_id = 1;
  string serving_endpoint = 2;
  bool is_control = 3;
  string assignment_reason = 4;
}

message GetVariantsRequest {
  string user_id = 1;
  repeated string experiment_ids = 2;
}

message GetVariantsResponse {
  map<string, GetVariantResponse> assignments = 1;
}
